project:
  type: website
  render:
    - "*"

jupyter: web
      
website:
  title: 'Benjamin Basseri'
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: blog.qmd
        text: Blog
  site-url: https://benjaminb.github.io

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
